host: "localhost:8200"
clients:
  - client_ip: "localhost:5000"
    client_id: "client1"
  - client_ip: "localhost:5001"
    client_id: "client2"
  - client_ip: "localhost:5002"
    client_id: "client3"

